spring:
  application:
    name: study-jpa

  datasource:
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    url: ${MYSQL_CONNECTION_URL}
    driver-class-name:  ${MYSQL_DRIVER}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        cache:
          use_second_level_cache: true
          region:
            factory_class: jcache
        javax:
          cache:
            provider: org.ehcache.jsr107.EhcacheCachingProvider
        format_sql: true
    show-sql: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

server:
  port: 8080
